name: my_library
description: A flutter project

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.2
  flutter_bloc: 8.1.3
  freezed_annotation: 2.2.0
  injectable: 2.1.2
  get_it: 7.6.0
  intl: 0.18.0
  dio: 5.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: 2.3.5
  flutter_gen_runner: 5.3.1
  injectable_generator: 2.1.6
    
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

flutter_intl:
  enabled: true
  arb_dir: assets/l10n
  output_dir: lib/generated

flutter_gen:
  output: lib/generated 
  line_length: 80
  assets:
    output:
      enabled: true
      package_parameter_enabled: false