import 'package:flutter/material.dart';
import 'package:my_library/design_system/ds_app_bar.dart';
import 'package:my_library/design_system/ds_color.dart';
import 'package:my_library/design_system/ds_spacing.dart';
import 'package:my_library/design_system/ds_text_style.dart';

class ReadingPage extends StatelessWidget {
  const ReadingPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const DSAppBar(
        title: 'Harry Potter',
      ),
      body: _buildBodyWidget(),
    );
  }

  Widget _buildBodyWidget() {
    return SingleChildScrollView(
      child: Padding(
        padding:
            const EdgeInsets.only(left: 30, right: 20, top: 20, bottom: 20),
        child: Column(
          children: [
            Text(
              'Harry Potter',
              style: DSTextStyle.ws20w700,
            ),
            Text(
              '-- J.K.Rowling --',
              style: DSTextStyle.ws16w400.copyWith(
                color: AppColors.grey500,
              ),
            ),
            SH10,
            Text(
              "Malfoy không thèm đến lớp mấy ngày; mãi đến xế ngày thứ năm, khi học sinh nhà Slytherin và Gryffindor đang học chung hai tiết môn Độc dược, nó mới xuất hiện. Nó khệnh khạng bước vào căn hầm dùng làm lớp học Độc dược, tay phải quấn băng, treo trước ngực như thể (theo nhận xét của Harry) nó là một kẻ sống sót đầy hào hùng sau một trận chiến kinh hoàng nào đó.\n"
              "Pansy Parkinson nở nụ cười hết sức điệu, hỏi:\n"
              "\"Đỡ chưa, anh Draco? Chắc là đau lắm hả?\"\n"
              "Malfoy mỉm một nụ cười ra vẻ can đảm:\n"
              "\"Ừ, đau lắm.\"\n"
              "Nhưng Harry nhận thấy khi Pansy nhìn qua hướng khác, Malfoy nháy mắt với Crabbe và Goyle.\n"
              "Giáo sư Snape lơ đễnh bảo:\n"
              "\"Ngồi xuống, ngồi xuống!\"\n"
              "Harry và Ron đưa mắt nhìn nhau tức tối. Nếu mà tụi nó bước vào lớp trễ thì đừng có mà hòng nghe thầy Snape bảo \"Ngồi xuống.\" Ông cho tụi nó cấm túc ngay ấy chứ. Nhưng Malfoy thì luôn luôn thoát được bất cứ lỗi gì nó phạm trong lớp học của thầy Snape. Giáo sư Snape, chủ nhiệm nhà Slytherin, luôn luôn thiên vị rõ rệt và rất hào phóng đối với học sinh ông chủ nhiệm trước mọi học sinh nhà khác.\n"
              "Hôm nay, bọn trẻ bào chế một món thuốc mới: Dung dịch Co rút.\n"
              "Malfoy đặt cái vạc của nó cạnh bên vạc của Ron và Harry, để cả ba cùng chuẩn bị nguyên liệu trên một cái bàn. Malfoy kêu:\n"
              "\"Thưa thầy, con cần một người giúp con cắt mấy rễ cúc này, bởi vì tay của con...\"\n"
              "Thầy Snape không cần nhìn lên, nói ngay:\n"
              "\"Ron, trò cắt rễ cúc giúp Malfoy.\"\n"
              "Mặt Ron đỏ nhừ. Nó rít vào mặt Malfoy:\n"
              "\"Tay mày có què cụt gì đâu!\"\n"
              "Malfoy ngồi bên kia bàn cười ngạo ngược:\n"
              "\"Ê, Ron, mày nghe giáo sư Snape bảo mà, cắt ba mớ rễ đó đi.\"\n"
              "Ron chụp con dao, kéo mớ rễ cúc của Malfoy lại gần, bắt đầu băm vằm chúng thành những mẩu nham nhở đủ kích cỡ. Malfoy lại kêu lên bằng giọng nhừa nhựa:\n"
              "\"Thưa thầy, Ron nó băm vằm rễ cúc của con, thầy ơi.\"\n"
              "Thầy Snape đến gần bàn của tụi nó, chĩa cái mũi khoằm của ông xuống mớ củ rễ, mỉm một nụ cười khó chịu với Ron qua mái tóc đen dài và bóng nhờn của ông:\n"
              "\"Ron, đổi rễ cho Malfoy.\"\n"
              "\"Nhưng, thưa thầy...!\"\n"
              "Ron đã tiêu hết mười lăm phút để mà tỉ mỉ tỉ mẩn gọt đẽo mớ rễ của nó cho có hình thù kích thước giống hệt nhau. Nhưng bằng giọng nói đầy nguy hiểm nhứt, thầy Snape bảo:\n"
              "\"Nào, đổi ngay.\"\n"
              "Ron hất mớ rễ được cắt tỉa xinh xắn của nó qua mặt bàn về phía Malfoy. Nó lại chụp lấy con dao tiếp tục gọt tỉa nữa.\n"
              "Malfoy lại nói, giọng chứa đầy tiếng cười độc địa:\n"
              "\"Và thưa thầy, con cần người lột vỏ trái Sung-quéo cho con ạ.\"\n"
              "Thầy Snape ném cho Harry một cái nhìn căm ghét mà ông luôn luôn chỉ dành riêng cho nó.\n"
              "\"Harry, trò lột vỏ Sung-quéo cho Malfoy đi.\"\n"
              "Harry cầm trái Sung-quéo của Malfoy trong khi Ron chuẩn bị thử trau chuốt lại mớ rễ cúc mà nó đã băm vằm nham nhở. Harry lột vỏ trái Sung-quéo thiệt nhanh rồi quăng trả qua bên kia bàn cho Malfoy mà không nói lời nào. Malfoy toét miệng cười đắc ý hơn bao giờ hết. Rồi nó thản nhiên hỏi:\n"
              "\"Dạo này có gặp lão bạn Hagrid của mày không?\"\n"
              "\"Không mắc mớ gì tới mày.\"\n"
              "Ron đáp nhát gừng, không thèm nhìn lên. Malfoy giở giọng buồn rầu mỉa mai:\n"
              "\"Tao e là ổng sẽ không bao giờ làm thầy giáo nữa. Ba tao không được hài lòng lắm về những thương tích của tao...\"\n"
              "Ron gầm gừ:\n"
              "\"Mày cứ nói nữa đi Malfoy, tao sẽ ày bị thương thiệt, khỏi cần giả đò.\"\n"
              "\"Ba tao đã phàn nàn với Hội đồng quản trị nhà trường và với Bộ Pháp Thuật. Mày biết mà, ba tao có nhiều thế lực lắm. Và một vết thương lâu lành như vầy...\"\n"
              "Nó thở dài một cái thiệt to đầy giả tạo:\n"
              "\"... ai biết được là rồi đây tay của tao có lành lặn lại như xưa không?\"\n"
              "Harry giận đến nỗi tay nó run lên, ngẫu nhiên mà cắt đứt đầu của một cái xác sâu bướm. Harry nói:\n"
              "\"Vậy ra đó là cái cớ mày bày đặt ra để làm cho bác Hagrid bị đuổi?\"\n"
              "Malfoy hạ giọng xuống thành những lời thì thào:\n"
              "\"Ừ, một phần thôi, Harry à. Nhưng mà cũng có những lợi ích khác nữa. Ê, Ron, cắt lát con sâu bướm dùm tao coi.\"\n"
              "Cách đó vài cái vạc, Neville cũng đang gặp rắc rối. Hễ tới giờ học môn Độc dược là Neville thường xuyên khốn đốn đến te tua. Đó là môn nó học dở nhứt, và nỗi sợ hãi khủng khiếp đối với thầy Snape làm cho tình thế của nó thêm mười lần khốn đốn hơn. Món thuốc của nó, lẽ ra phải màu xanh tươi, đã ngả màu...\n"
              "\"Cam! Có thấy không, Longbottom?\"\n"
              "Thầy Snape quát. Ông cầm cái muôi múc thuốc lên rồi rót nó trở xuống cái vạc, để ọi người có thể nhìn thấy.\n"
              "\"Màu cam. Thử nói cho tôi nghe coi, ông tướng, cái sọ dầy mo của ông có hấp thụ được cái thứ gì không? Ông không nghe tôi nói sao, rất rõ ràng rằng, chỉ cần một cái lá lách của con chuột nhắt là đủ? Tôi đã chẳng trình bày hết sức hiển nhiên sao, rằng một chút xíu nhớt của con đỉa là đủ rồi? Tôi còn phải làm gì nữa để cho ông hiểu hả ông Longbottom?\"\n"
              "Neville run như cầy sấy và thẹn hồng cả mặt mũi. Trông nó như sắp òa khóc. Hermione nói:\n"
              "\"Thưa thầy, xin thầy vui lòng... vui lòng cho con giúp Neville sửa chữa lại ạ...\"\n"
              "Thầy Snape lạnh lùng nạt:\n"
              "\"Tôi nhớ tôi đâu có bảo cô khoe mẽ đâu, cô Granger.\"\n"
              "Hermione cũng ngượng đỏ y như Neville. Thầy Snape nói tiếp:\n"
              "\n"
              "\n"
              "\"Longbottom, cuối buổi học này, chúng ta sẽ cho con cóc của trò nếm vài giọt thuốc này để xem chuyện gì xảy ra. Có thể điều đó sẽ cổ vũ trò làm ăn đúng đắn hơn.\"\n"
              "Thầy Snape bỏ đi, để mặc Neville nín thở vì khiếp đảm. Nó rên rỉ với Hermione:\n"
              "\"Giúp mình với!\"\n"
              "\"Ê, Harry!\"\n"
              "Seamus chồm tới để mượn cái cân đồng của Harry, hỏi:\n"
              "\"Bồ có nghe chưa? Tờ Nhật báo Tiên Tri sáng nay đăng tin... họ cho là đã tìm ra dấu vết của Sirius Black.\"\n"
              "Harry và Ron cùng nhanh nhẩu hỏi lại:\n"
              "\"Ở đâu?\"\n"
              "Bên kia bàn, Malfoy cũng dỏng tai lên nghe lóm. Seamus nói, có vẻ hồi hộp lắm:\n"
              "\"Cách đây không xa... Chính một Muggle đã nhìn thấy hắn. Dĩ nhiên tại bả không hiểu rõ vấn đề. Dân Muggle chỉ nghĩ hắn là một tội phạm thông thường, phải không? Cho nên bả gọi điện thoại cho đường dây nóng. Khi Bộ Pháp thuật đến nơi thì hắn đã chuồn mất rồi.\"\n"
              "Ron nhìn Harry một cách đầy ngụ ý, lập lại:\n"
              "\"Cách đây không xa...\"\n"
              "Ron quay đầu lại, bắt gặp Malfoy đang nhìn Harry rất sát. Ron hỏi:\n"
              "\"Gì vậy, Malfoy? Cần lột vỏ cái gì nữa hả?\"\n"
              "Nhưng đôi mắt Malfoy đang sáng lên một cách nham hiểm và cứ nhìn chằm chằm vào Harry. Nó chồm qua bàn:\n"
              "\"Harry, mày tính một tay bắt gọn Sirius Black hả?\"\n"
              "Harry đáp lời không cần khách sáo:\"\n"
              "\"Ừ, đúng vậy.\"\n"
              "Miệng Malfoy cong lên thành một nụ cười hiểm độc. Nó nói thản nhiên:\n"
              "\"Dĩ nhiên nếu là tao thì tao đã làm được điều gì đó, tao sẽ chẳng ở lại trường như một cậu bé ngoan hiền, mà tao sẽ xông ra ngoài tìm kiếm hắn.\"\n"
              "Ron hỏi một cách thô lỗ:\n"
              "\"Mày đang nói về cái gì vậy Malfoy?\"\n"
              "Đôi mắt nhợt nhạt của Malfoy nheo lại:\n"
              "\"Mày không biết gì sao, Harry?\"\n"
              "\"Biết gì?\"\n"
              "Malfoy phì ra một tiếng cười nhỏ, khinh khỉnh:\n"
              "\"Có lẽ mày không nên liều mạng làm gì. Cứ giao việc đó cho các viên giám ngục Azkaban, đúng không? Nhưng nếu là tao, tao sẽ trả thù. Tao sẽ tự mình tìm hắn mà thanh toán.\"\n"
              "Harry tức giận hỏi:\n"
              "\"Mày đang nói về cái gì hả?\"\n"
              "Nhưng lúc đó thầy lên tiếng:\n"
              "\"Tới giờ thì các trò đã tính toán thêm vô đủ các nguyên vật liệu rồi. Món thuốc này cần được sắc kỹ trước khi uống. Khi nào nó sủi tăm sắp sôi thì nhấc ra, lúc đó chúng ta sẽ thử nghiệm với con cóc của Longbottom...\"\n"
              "Crabbe và Goyle phá ra cười công khai. Hai đứa nó nhìn Neville toát mồ hôi trong lúc cố khuấy cái vạc thuốc như điên. Hermione đang lầm rầm đọc lời chỉ dẫn cho Neville, môi mép cô bé chỉ nhếch khẽ, đủ để cho thầy Snape không nhìn thấy. Harry và Ron dọn dẹp những nguyên vật liệu mà tụi nó không dùng nữa, rồi đi rửa tay và rửa mấy cái muôi ở chậu đá trong góc phòng.\n"
              "Harry thì thầm với Ron khi nó chìa bàn tay ra dưới dòng nước lạnh như nước đá chảy ra từ một cái miệng máng xối:\n"
              "\"Malfoy muốn nói gì vậy? Tại sao mình lại muốn trả thù Black? Hắn đâu có làm gì mình đâu, ít ra là chưa...\"\n"
              "Ron đáp, vẻ hung dữ:\n"
              "\"Nó bịa ra chuyện đó. Nó đang tìm cách xúi bồ làm một chuyện ngu ngốc gì đó đấy mà...\"\n"
              "Gần cuối buổi học, thầy Snape bước dài về phía Neville. Thằng bé co rúm lại bên cái vạc của mình. Đôi mắt đen của thầy Snape sáng lấp lánh. Thầy gọi:\n"
              "\"Mọi người hãy tụ tập lại đây và xem coi điều gì xảy ra cho con cóc của Longbottom. Nếu mà Longbottom đã xoay sở bào chế ra đúng Dung dịch Co rút thì con cóc sẽ co lại thành con nòng nọc. Nếu trò ấy làm sai, tôi không nghi ngờ khả năng này, thì con cóc sẽ trông như thể bị đầu độc.\"\n"
              "Đám học sinh nhà Gryffindor nhìn mà chết khiếp. Còn đám học sinh nhà Slytherin thì khoái chí ra mặt. Thầy Snape bốc con cóc Trevor lên bằng tay trái, và nhúng một cái muỗng nhỏ vô vạc thuốc của Neville. Bây giờ món thuốc Neville bào chế đã có màu xanh. Thầy nhễu vài giọt xuống cổ họng con Trevor.\n"
              "Trong tích tắc mà con Trevor nuốt mấy giọt thuốc, cả phòng học im phăng phắc. Rồi một tiếng nổ bụp vang lên, và con nòng nọc Trevor ngoe nguẩy bơi trong lòng bàn tay của thầy Snape.\n"
              "Bọn nhà Gryffindor hè nhau vỗ tay hoan hô. Thầy Snape, vẻ cáu kỉnh hết chỗ nói, rút trong túi áo chùng của thầy ra một cái chai nhỏ, rót vài giọt lên con Trevor và con cóc thình lình tái xuất hiện, đã trưởng thành hoàn toàn.\n"
              "\"Trừ nhà Gryffindor năm điểm.\"\n"
              "Tiếng thầy Snape vang lên làm tắt ngấm mọi nụ cười trên gương mặt học sinh nhà Gryffindor. Lý do trừ điểm là:\n"
              "\"Hermione, tôi đã bảo trò không được giúp Longbottom mà trò không chịu nghe. Lớp học giải tán.\"\n"
              "Harry, Ron và Hermione trèo lên bậc thềm đến Tiền sảnh. Harry vẫn còn nghĩ lẩn quẩn về những điều Malfoy nói. Ron thì nổi cáu về vụ thầy Snape. Nó chì chiết Hermione:\n"
              "\"Trừ nhà Gryffindor năm điểm chỉ vì món thuốc được bào chế đúng! Tại sao bồ không nói dối, Hermione? Lẽ ra bồ phải nói là tự một mình Neville bào chế ra món thuốc đó chứ!\"\n"
              "Nhưng không nghe Hermione trả lời. Ron nhìn quanh quất:\n"
              "\"Ủa, bạn ấy đâu rồi?\"\n"
              "Harry cũng quay lại nhìn quanh. Bây giờ tụi nó đang đứng ở đầu bậc thềm, quan sát những học sinh khác đi ngang qua tụi nó đến Đại Sảnh đường để ăn trưa. Ron nói, giọng nghiêm trọng:\n"
              "\"Bạn ấy đi ngay đằng sau mình mà.\"\n"
              "Malfoy đi ngang qua, hai bên là Crabbe và Goyle. Nó nở nụ cười tự mãn với Harry rồi biến mất. Harry kêu:\n"
              "\"Kìa, bạn ấy kìa.\"\n"
              "Hermione đang vội vã leo lên bậc thềm, thở hơi gấp một tý, một bàn tay cô bé túm chặt cái túi xách của mình, tay kia dường như giấu cái gì dưới vạt trước của cái áo chùng. Ron nói:\n"
              "\n"
              "\n"
              "\"Làm sao bồ làm được chuyện đó?\"\n"
              "Hermione nhập bọn với hai bạn, hỏi lại:\n"
              "\"Chuyện gì?\"\n"
              "\"Mới phút trước bồ còn ở ngay phía sau lưng tụi này, mà chỉ một phút sau bồ đã lại ở tuốt dưới bậc thềm cuối của cầu thang rồi.\"\n"
              "Hermione có vẻ hơi bối rối:\n"
              "\"Cái gì? À... mình phải trở lại lấy một thứ. Ối, không...\"\n"
              "Một đường rách làm tét cái túi xách của Hermione. Harry không lấy làm lạ chút nào. Nó có thể thấy cái túi bị quá tải, với ít nhứt một tá sách dầy cui nặng ịch nhét trong đó. Ron hỏi:\n"
              "\"Việc gì bồ phải vác hết những thứ này đi theo?\"\n"
              "Hermione nói hụt hơi:\n"
              "\"Bồ biết mình theo học bao nhiêu môn không? Bồ không thể cầm nổi mấy cuốn này giùm mình hay sao?\"\n"
              "Ron lật mấy cuốn sách Hermione đưa nó, thốt kêu:\n"
              "\"Nhưng... bồ đâu có học mấy môn này bữa nay. Môn Phòng chống Nghệ thuật Hắc ám có lớp vào chiều nay mà!\"\n"
              "Hermione đáp mập mờ:\n"
              "\"Ờ...\"\n"
              "Cô bé lại nhét hết sách vở vô túi xách như cũ. Rồi cô bé bỏ đi, hướng về phía Đại Sảnh đường, nói thêm:\n"
              "\"Mình hy vọng bữa trưa nay có món gì ngon ngon. Mình đang đói muốn chết luôn.\"\n"
              "Ron hỏi Harry:\n"
              "\"Bộ bồ không cảm thấy là Hermione đang có điều gì đó không chịu nói cho tụi mình biết sao?\"\n"
              "*****\n"
              "Khi bọn trẻ đến lớp Phòng chống Nghệ thuật Hắc ám để học bài đầu tiên thì giáo sư Lupin vẫn chưa có mặt ở đó. Bọn chúng bèn ngồi xuống, lấy sách, giấy da, và viết lông ngỗng ra, rồi tán dóc cho đến khi thầy Lupin bước vào lớp. Thầy mỉm cười mơ hồ và đặt cái cặp cũ kỹ tồi tàn của thầy lên bàn giáo viên. Trông thầy vẫn xoàng xĩnh như từ trước tới giờ, nhưng có vẻ khỏe mạnh hơn hồi ở trên xe lửa, như thể đã được ăn vài bữa no nê. Thầy nói:\n"
              "\"Chào các trò. Các trò hãy vui lòng cất hết sách vào cặp. Hôm nay là bài học thực hành, các trò chỉ cần đến cây đũa phép mà thôi.\"\n"
              "Cả lớp cất sách đi, vài người trao đổi nhau cái nhìn tò mò. Trước đây, tụi nó chưa từng thực hành Phòng chống Nghệ thuật Hắc ám bao giờ. Ấy là không kể buổi học đáng nhớ năm ngoái, khi thầy giáo cũ dạy môn này mang vào lớp cả một cái chuồng chứa đầy bọn yêu nhí rồi thả chúng ra.\n"
              "Giáo sư Lupin nói khi mọi người đã sẵn sàng:\n"
              "\"Tốt lắm. Mời các trò làm theo tôi.\"\n"
              "Bọn học trò hơi bối rối nhưng mà thích thú đứng dậy đi theo giáo sư Lupin ra khỏi phòng học. Ông dắt bọn trẻ đi dọc một hành lang vắng vẻ rồi quẹo qua một góc, ở đó cái mà bọn trẻ nhìn thấy trước tiên là con yêu tinh Peeves. Nó đang lộn đầu xuống đất, cất cẳng lên trời, lơ lửng giữa không trung, và đang nhét kẹo cao su vô cái lỗ khóa gần nhứt.\n"
              "Khi giáo sư Lupin đến cách Peeves chừng hai thước, con yêu tinh mới ngẩng đầu lên. Nó ngọ nguậy hai bàn chân có những ngón chân cong quèo và hát toáng lên:\n"
              "\"Lupin khùng, Lupin điên\n"
              "Lupin khùng, Lupin điên\"\n"
              "Xưa nay Peeves hầu như luôn luôn hỗn hào bất trị như vậy, tuy cũng biết bày tỏ ít nhiều kính trọng kiểu gì đó đối với các giáo sư. Mọi người đều nhìn giáo sư Lupin để xem ông phản ứng ra sao về chuyện này. Bọn trẻ ngạc nhiên thấy giáo sư Lupin vẫn mỉm cười. Ông nói một cách dễ thương:\n"
              "\"Nếu tôi là chú em, thì tôi sẽ gỡ bỏ hết cao su dính trong mấy lỗ khóa đó. Để vậy, coi chừng thầy Filch sẽ khó có thể vô trong đó lấy chổi.\"\n"
              "Thầy Filch giám thị trường Hogwarts, một phù thủy bất bài, tính tình nóng nảy, người tiến hành cuộc chiến thường xuyên chống bọn học trò và, đúng vậy, chống cả Peeves nữa. Nhưng Peeves chẳng mảy may bận tâm đến những lời giáo sư Lupin nói, ngoài chuyện bỏ hai ngón tay vào miệng huýt sáo thật to.\n"
              "Giáo sư nhẹ thở dài và rút cây đũa phép ra. Thầy ngoảnh đầu lại nói qua vai mình với đám học trò:\n"
              "\"Đây là một lời nguyền nho nhỏ rất hữu ích, các trò hãy quan sát cho kỹ.\"\n"
              "Ông giơ cây đũa phép lên tầm cao ngang vai, đọc: \"waddiwasi!\", rồi chĩa đầu đũa vào Peeves. Bằng sức mạnh của một đầu đạn, miếng kẹo cao su văng ra khỏi lỗ khóa và phóng thẳng vô lỗ mũi bên trái của Peeves. Con yêu tinh lộn mèo như cơn lốc, bốc lên, chửi rủa và biến đi.\n"
              "Dean Thomas hết sức kinh ngạc:\n"
              "\"Hết sẩy, thưa thầy!\"\n"
              "Giáo sư Lupin cất cây đũa phép đi và nói:\n"
              "\"Cám ơn, Dean. Chúng ta tiếp tục được chứ?\"\n"
              "Thầy trò lại tiếp tục đi tới, cả lớp bây giờ nhìn thầy Lupin xoàng xĩnh với một niềm kính trọng được tăng lên đáng kể. Thầy dẫn đám học trò đi xuống hành lang thứ hai và dừng lại, ngay bên ngoài cửa phòng hội đồng giáo viên. Thầy Lupin mở cửa rồi đứng qua một bên nói:\n"
              "\"Mời vào bên trong.\"\n"
              "Phòng hội đồng giáo viên là một phòng ốp gỗ đầy những cái ghế để lộn xộn không ai ngồi, trừ một cái. Giáo sư Snape đang ngồi trên một cái ghế bành thấp. Đôi mắt thầy Snape sáng long lanh và môi thầy thấp thoáng nụ cười nhạo báng độc địa. Giáo sư Lupin bước vào, khép lại cánh cửa phía sau lưng. Giáo sư Snape bèn nói:\n"
              "\"Cứ để cửa mở, Lupin. Tôi chẳng hứng thú chứng kiên trò này lắm đâu.\"\n"
              "Rồi thầy Snape đứng dậy, sải bước đi ngang qua bọn học trò, tấm áo chùng đen của ông phồng lên phơ phất sau bước chân. Đến cửa, giáo sư Snape quay ngoắt một vòng trên gót, và nói:\n"
              "\"Có lẽ chưa ai khuyến cáo ông, ông Lupin à, nhưng lớp này có một trò tên là Neville Longbottom. Tôi muốn khuyên ông đừng có giao cho trò đó bất cứ việc khó khăn nào, trừ khi có trò Hermione nhắc tuồng bên tai nó.\"\n"
              "Neville đỏ mặt. Harry nhìn thầy Snape trừng trừng; hành hạ Neville ở ngay trong lớp thầy đã đủ tệ rồi, giờ lại còn làm cái chuyện đó ngay trước mặt các giáo viên khác.\n"
              "Giáo sư Lupin nhướn chân mày lên:\n"
              "\"Tôi đang trông mong Neville sẽ giúp tôi trong giai đoạn điều hành thứ nhứt, và tôi chắc chắn là trò ấy sẽ thực hiện điều đó một cách đáng nể.\"\n"
              "Mặt Neville càng đỏ thêm, như không thể đỏ thêm được nữa. Môi thầy Snape cong lên, nhưng ông bỏ đi, đóng cánh cửa kêu một cái rầm.\n"
              "Giáo sư vẫy tay ra hiệu cho cả lớp đi về phía cuối phòng:\n"
              "\"Thôi, bắt đầu.\"\n"
              "\n"
              "Cuối phòng không có gì cả ngoại trừ một cái tủ áo cũ mà các giáo sư thường cất những tấm áo chùng dự trữ. Khi giáo sư Lupin bước đến đứng cạnh bên cái tủ áo thì cái tủ bỗng nhiên lảo đảo lắc lư, dộng bức tường ầm ầm.\n"
              "Vài đứa học trò nhảy lùi lại cảnh giác. Giáo sư Lupin bèn bình thản nói:\n"
              "\"Chẳng có gì đáng sợ cả. Trong đó có một Ông Kẹ.\"\n"
              "Hầu hết lũ học trò đều cảm thấy đó chính là cái đáng sợ. Neville nhìn thầy Lupin với ánh mắt chỉ còn có hãi hùng, và Seamus thì nhìn cái nắm đấm cửa tủ đang kêu lách cách với vẻ lo lắng bồn chồn.\n"
              "Giáo sư Lupin giảng giải:\n"
              "\"Mấy Ông Kẹ khoái những nơi đóng kín tối tăm, như tủ quần áo, gầm giường, chạn tủ dưới gầm chậu rửa bát... Có một lần tôi bắt gặp một Ông Kẹ trú ngụ ngay trong một cái đồng hồ đứng cổ lỗ sĩ. Ông Kẹ này mới dọn vô đây vào trưa ngày hôm qua, và tôi đã xin phép ông Hiệu trưởng yêu cầu các giáo viên cứ để mặc nó ở đó để cho học sinh năm thứ ba có dịp thực tập. Vậy câu hỏi đầu tiên mà các trò phải tự hỏi là: Ông Kẹ là gì?\"\n"
              "Hermione giơ tay lên ngay:\n"
              "\"Đó là một con ma thay hình đổi dạng. Nó có thể đội lốt bất cứ cái gì mà nó tưởng làm cho chúng ta sợ nhứt.\"\n"
              "Giáo sư Lupin nói:\n"
              "\"Đúng lắm. Tôi cũng không thể nào giải thích rõ ràng hơn Hermione được.\"\n"
              "Mặt Hermione sáng rực lên. Giáo sư Lupin nói tiếp:\n"
              "\"Như thế khi Ông Kẹ còn ngồi trong bóng tối, nó chưa mang một hình dạng nào hết. Nó chưa biết cái nào sẽ hù dọa được người ở bên ngoài cánh cửa. Chưa có ai từng được biết một Ông Kẹ thì trông như thế nào khi nó ở một mình. Nhưng khi tôi thả nó ra khỏi tủ thì nó lập tức trở thành bất cứ cái gì mà mỗi chúng ta sợ nhứt.\"\n"
              "Neville thốt lên mấy tiếng ú ớ khiếp đảm, nhưng giáo sư Lupin phớt lờ đi, nói tiếp:\n"
              "\"Điều này có nghĩa là chúng ta có một thuận lợi lớn lao so với Ông Kẹ trước khi chúng ta bắt đầu. Trò có biết là gì không, Harry?\"\n"
              "Suy nghĩ câu trả lời khi bên cạnh là một Hermione cứ nhấp nha nhấp nhổm trên gót giày với cánh tay giơ tuốt trên cao quả là rất ư khó khăn, nhưng Harry cũng tìm được câu trả lời:\n"
              "\"Ơ... bởi vì chúng ta có nhiều người, Ông Kẹ không biết nên đội lốt nào.\"\n"
              "\"Chính xác!\"\n"
              "Cánh tay của Hermione đành hạ xuống thất vọng. Giáo sư Lupin nói tiếp:\n"
              "\"Luôn luôn nên có nhiều người khi xử lý Ông Kẹ. Con ma đội lốt sẽ bối rối. Nó nên đội lốt gì, một cái xác không đầu hay một con sên ăn thịt sống? Có một lần tôi thấy một Ông Kẹ phạm chính cái sai lầm đó: toan hù dọa hai người cùng một lúc và tự biến mình thành một nửa con sên. Không đến nỗi ghê lắm.\n"
              "\"Bùa chú để giải tà Ông Kẹ đơn giản thôi. Tuy nhiên cũng cần đến sức mạnh của ý chí. Các trò biết không, cái thực sự chấm dứt một Ông Kẹ là một trận cười. Điều các trò cần làm là buộc nó mang một hình dạng mà các trò thấy tức cười.\n"
              "\"Chúng ta sẽ thực tập câu thần chú trước, không cần dùng đến cây đũa phép. Các trò hãy nói theo tôi... riddikulus!\"\n"
              "Cả lớp đồng thanh lập lại:\n"
              "\"Riddikulus!\"\n"
              "Giáo sư Lupin nói:\n"
              "\"Tốt lắm! Rất tốt. Nhưng tôi e là mình chỉ vừa thực tập xong phần dễ làm. Các trò nên biết là chỉ mỗi cái từ đó thôi thì chưa đủ hiệu nghiệm. Và đây là lúc cần đến trò, Neville à.\"\n"
              "Cái tủ áo lại rung lắc bần bật, nhưng cũng không đến nỗi thảm như Neville: nó bước tới trước như thể nó đang đi tới cái giá treo cổ. Giáo sư Lupin nói:\n"
              "\"Được rồi, Neville. Hãy làm cái trước tiên trước: trò hãy nói xem cái gì làm cho trò sợ nhứt trên cõi đời này?\"\n"
              "Môi của Neville mấp máy, nhưng không ai nghe được tiếng nào. Giáo sư Lupin vui vẻ nói:\n"
              "\"Xin lỗi trò, tôi chưa nghe ra.\"\n"
              "Neville nhìn quanh với vẻ hoang mang, như thể cầu xin ai đó cứu giúp nó với, rồi nó nói, nghe như một tiếng thì thào:\n"
              "\"Giáo sư Snape.\"\n"
              "Hầu như ai cũng cười. Ngay cả Neville cũng mỉm cười với vẻ hối lỗi. Tuy nhiên giáo sư Lupin lại có vẻ suy tư.\n"
              "\"Giáo sư Snape... hừm... Neville, thầy nghĩ con sống với bà nội con, phải không?\"\n"
              "Neville lo lắng:\n"
              "\"Ơ... phải, nhưng mà con không muốn Ông Kẹ biến thành bà nội con đâu.\"\n"
              "\"Không, không, con hiểu lầm thầy rồi.\"\n"
              "Giáo sư Lupin bây giờ lại mỉm cười, nói tiếp:\n"
              "\"Thầy không biết con có thể nói ọi người biết loại áo quần gì mà bà của con thường mặc không?\"\n"
              "Neville có vẻ ngạc nhiên, nhưng cũng đáp:\n"
              "\"Dạ... Bà luôn luôn đội cái nón ấy, một cái nón cao trên đỉnh có gắn một con kền kền nhồi bông. Và một cái áo đầm dài màu xanh lá cây, thông thường... và đôi khi quàng khăn quàng cổ bằng lông cáo.\"\n"
              "Giáo sư Lupin gợi ý:\n"
              "\"Và một cái ví xách tay?\"\n"
              "Neville nói:\n"
              "\"Một cái màu đỏ bự lắm.\"\n"
              "Giáo sư Lupin nói:\n"
              "\"Được rồi. Con thể hình dung những thứ y phục này rõ ràng không, Neville? Con có thể nhìn thấy chúng ở trong đầu con không?\"\n"
              "\"Dạ.\"\n"
              "Neville đáp không chắc chắn chút nào, hiển nhiên là nó đang thắc mắc chuyện gì tiếp theo đây. Giáo sư Lupin tiếp tục giảng giải:\n"
              "\"Neville à, khi Ông Kẹ nhào ra khỏi cái tủ áo và trông thấy con, nó sẽ đội ngay lốt giáo sư Snape. Và con sẽ giơ cây đũa phép lên, như vầy, và la lên \"Riddikulus\", và hết sức tập trung nghĩ đến áo nón của bà con. Nếu con làm tốt thì \"giáo sư Snape\" sẽ bị đội cái nón có con kền kền nhồi bông trên chóp, mặc cái áo đầm xanh, đeo cái ví bự màu đỏ.\"\n"
              "Mọi người phá ra cười to. Cái tủ áo cũng lắc lư dữ dội. Giáo sư Lupin nói tiếp:\n"
              "\"Nếu Neville thành công, thì Ông Kẹ có thể hướng sự chú ý lần lượt vào từng người trong chúng ta. Tôi muốn tất cả các trò hãy dành ra ít phút bây giờ để nghĩ xem mình sợ cái gì nhứt, và nghĩ xem mình có thể ép nó làm gì cho thiệt khôi hài...\"\n"
              "Căn phòng trở nên im lặng. Harry nghĩ... Cái gì khiến nó sợ nhứt trên đời này?\n"
              "Ý nghĩ đầu tiên là Chúa tể Hắc ám Voldemort - một Voldemort lấy lại đầy đủ sức mạnh. Nhưng trước khi nó nghĩ ra một kế hoạch có thể phản công lại Ông Kẹ - Voldemort, thì một hình ảnh khủng khiếp lướt thoáng qua đầu nó...\n"
              "Một bàn tay nát rữa, nhầy nhụa, loang thoáng, thụt vào bên trong lớp áo trùm đen... một hơi thở dài rung leng keng từ một cái miệng không nhìn thấy được... rồi một cơn lạnh buốt thấu xương như bị chết đuối...\n"
              "Harry rùng mình, rồi nhìn quanh, hy vọng không ai để ý. Nhiều người nhắm tịt mắt lại. Ron đang thì thầm với chính mình: \"Gỡ chân nó ra!\" Harry đoan chắc là nó hiểu ý nghĩa câu đó: nỗi sợ hãi lớn nhứt của Ron là nhền nhện.\n"
              "Giáo sư Lupin hỏi:\n"
              "\"Mọi người sẵn sàng chưa?\"\n"
              "Harry cảm thấy một nỗi kinh hoàng quặn trào lên trong người nó. Làm sao để khiến ột viên giám ngục Azkaban trông bớt ghê sợ đi? Nhưng nó không muốn xin thêm thời gian nữa; mọi người khác đều đã gật đầu và xắn tay áo lên. Giáo sư Lupin nói:\n"
              "\"Neville, chúng ta sẽ lùi lại một chút, để cho con có một bãi đấu thoáng rõ, được chứ? Các trò cũng lùi lại hết, tôi sẽ gọi người tiếp theo tới trước... Bây giờ, Neville có thể nhìn thấy rõ hơn...\"\n"
              "Tất cả đều thối lui, đứng dựa sát tường để lại một mình Neville bên cái tủ áo. Trông nó xanh xao không còn hồn vía, nhưng nó đã xắn tay áo lên và nắm chặt cây đũa phép trong tay, sẵn sàng.\n"
              "Giáo sư Lupin giơ cây đũa phép của ông về phía nắm đấm của cánh cửa tủ:\n"
              "\n"
              "\n"
              "\"Thầy đếm đến ba, Neville nhé. Một - hai - ba! Bắt đầu!\"\n"
              "Một chùm lửa sáng xẹt ra từ đầu đũa phép của giáo sư Lupin, trúng ngay cái nắm đấm. Cái tủ áo mở bung ra. Giáo sư Snape bước ra, mũi khoằm, vẻ dọa nạt, quắc mắt nhìn Neville.\n"
              "Neville lùi lại, đũa phép giơ lên, miệng há hốc không thốt ra lời. Thầy Snape tiến về phía nó, đè trùm lên nó, cho tay vào bên trong lớp áo chùng. Neville chợt thét lên:\n"
              "\"R-r-riddikulus!\"\n"
              "Có một tiếng gì vang lên như tiếng roi quất. Thầy Snape loạng choạng. Rồi thầy mặc một cái áo đầm dài viền ren, đội một cái nón cao trên chóp có một con kền kền bị mối gặm, và tay đung đưa một cái ví bự chảng màu đỏ thắm.\n"
              "Một tràng cười bùng vỡ; còn Ông Kẹ khựng lại; bối rối, và giáo sư Lupin hét:\n"
              "\"Parvati! Tiến lên!\"\n"
              "Parvati bước tới trước, vẻ mặt đã chuẩn bị. Thầy Snape quay lại cô bé. Một tiếng rắc nữa vang lên, chỗ thầy Snape vừa đứng hiện ra một xác ướp quấn khăn liệm chằng chịt đầy vết máu hoen. Gương mặt quấn kín của cái xác ướp quay về phía Parvati và bắt đầu đi về phía cô bé, một cách chậm chạp, lê lết trên đôi chân cứng ngắc, và đôi tay cứng đơ giơ lên... Parvati hét:\n"
              "\"Riddikulus!\"\n"
              "Một miếng băng ở chân xác ướp bị xổ ra, vướng vô chân xác ướp, khiến nó té nhào tới trước, cái đầu lăn đi lông lốc. Giáo sư Lupin hô to:\n"
              "\"Seamus!\"\n"
              "Seamus phóng qua mặt Parvati.\n"
              "Rắc! Chỗ vừa rồi là cái xác ướp bây giờ hiện ra một người đàn bà tóc đen dài chấm đất, gương mặt xanh lét trơ xương - chính là Nữ thần báo tử. Bà ta há miệng rộng hoác, một tiếng gì vô cùng bí hiểm tràn ngập căn phòng, một tiếng rít than vãn rợn óc làm dựng cả tóc gáy Harry. Seamus gào:\n"
              "\"Riddikulus!\"\n"
              "Nữ thần báo tử kêu lên mấy tiếng cọt kẹt và chẹn lấy cổ họng mình, tiếng của bà ta tắt lịm.\n"
              "Rắc! Nữ thần báo tử biến thành một con chuột nhắt, một con chuột cứ xoay vòng vòng cắn cái đuôi của mình, và rồi - Rắc! - biến thành một con rắn rung chuông, quằn quại trườn đi trước khi - Rắc! - biến thành một tròng mắt đẫm máu.\n"
              "Thầy Lupin la lên:\n"
              "\"Nó lúng túng rồi! Chúng ta sắp thành công! Dean!\"\n"
              "Dean vội vã chạy tới trước.\n"
              "Rắc! Tròng mắt biến thành một bàn tay mộc mạc, nó búng một cái rồi bắt đầu bò trên sàn như một con cua. Dean gào lên:\n"
              "\"Riddikulus!\"\n"
              "Nghe tách một cái, thế là bàn tay bị mắc vô cái bẫy chuột.\n"
              "\"Xuất sắc! Ron, tiếp theo!\"\n"
              "Ron nhảy vọt tới trước.\n"
              "Rắc!\n"
              "Cả đống người rú lên. Một con nhền nhện khổng lồ phủ đầy lông lá, cao chừng hai thước đang tiến về phía Ron, nhắp nhắp đôi càng đầy đe dọa. Trong khoảnh khắc, Harry nghĩ là Ron đã bị đông cứng lại. Thế rồi...\n"
              "\"Riddikulus!\"\n"
              "Ron rống lên, sáu cái chân nhền nhện biến mất. Con nhền nhện không chân cứ lăn tròn lăn tròn. Lavender hét toáng lên, chạy tránh ra khỏi đường lăn của con nhền nhện. Nó lăn tới chân của Harry thì ngừng lại. Harry giơ cây đũa lên sẵn sàng, nhưng... Giáo sư Lupin thình lình la lên:\n"
              "\"Đây rồi!\"\n"
              "Ông hối hả chạy tới. Rắc! Con nhền nhện không chân biến mất. Trong một giây mọi người ngơ ngác nhìn quanh coi nó ở đâu. Chúng thấy một trái cầu pha lê trắng óng ánh bạc lơ lửng trên không phía trước giáo sư Lupin. Ông uể oải nói:\n"
              "\"Riddikulus!\"\n"
              "Rắc!\n"
              "Con Ông Kẹ đáp xuống sàn thành một con gián quèn. Thầy Lupin lại gọi:\n"
              "\"Neville, tiến lên, và kết thúc nó luôn!\"\n"
              "Rắc!\n"
              "Giáo sư Lupin lùi lại. Lần này Neville lao tới trước với vẻ quả quyết ra mặt.\n"
              "\"Riddikulus!\"\n"
              "Neville hét to, và trong nửa giây, mọi người nhìn thấy hình ảnh thầy Snape trong trang phục đàn bà đầu rua ren, rồi Neville bật ra một tràng cười \"Ha ha ha...\", và con Ông Kẹ nổ tung thành cả ngàn bụm khói nho nhỏ, xong biến mất.\n"
              "Giáo sư Lupin thốt lên:\n"
              "\"Xuất sắc!\"\n"
              "Lớp học lại ào lên vỗ tay hoan hô. Giáo sư Lupin nói:\n"
              "\"Xuất sắc! Neville. Mọi người đều làm giỏi lắm. Để tôi xem, năm điểm cho nhà Gryffindor ỗi học sinh đã tham gia khắc phục con Ông Kẹ, riêng Neville thì được mười điểm vì làm đến hai lần... Harry và Hermione cũng được mỗi người năm điểm.\"\n"
              "Harry nói:\n"
              "\"Nhưng thưa thầy, con có làm gì đâu?\"\n"
              "Thầy Lupin nhẹ nhàng nói:\n"
              "\"Trò và Hermione đã trả lời đúng câu hỏi của ta vào đầu buổi học, Harry à. Mọi người đều rất giỏi, bài học hôm nay thật xuất sắc. Bài tập về nhà, hãy vui lòng đọc chương về Ông Kẹ, và tóm tắt lại cho tôi... và nộp bài vào thứ hai. Bấy nhiêu đó thôi.\"\n"
              "Bọn trẻ rời căn phòng, nói chuyện hào hứng. Tuy nhiên Harry không cảm thấy phấn khởi lắm. Giáo sư Lupin đã cố tình không cho nó đối phó với Ông Kẹ. Tại sao? Có phải vì ông đã nhìn thấy Harry đổ gục trên xe lửa, và nghĩ là nó không làm nổi chuyện đó chăng? Chẳng lẽ ông nghĩ Harry có thể xỉu một lần nữa?\n"
              "Nhưng không ai có vẻ để ý điều gì cả. Seamus la lớn:\n"
              "\"Mấy bồ có thấy tôi trị Nữ thần báo tử không?\"\n"
              "Dean vẫy bàn tay của chính nó khắp xung quanh:\n"
              "\"Và bàn tay ma nữa!\"\n"
              "\"Và thầy Snape đội cái nón ấy!\"\n"
              "\"Và cái xác ướp của tôi nữa!\"\n"
              "Chỉ có Lavender nói một cách ưu tư:\n"
              "\"Mình thắc mắc tại sao giáo sư Lupin lại sợ trái cầu pha lê nhỉ?\"\n"
              "Khi tụi nó quay trở về phòng học để lấy lại cặp sách, Ron thích thú nói:\n"
              "\"Đây là bài học Phòng chống Nghệ thuật Hắc ám hay nhứt từ trước tới nay, đúng không?\"\n"
              "Hermione công nhận:\n"
              "\"Thầy có vẻ là một giáo viên giỏi. Nhưng mình ước gì mình cũng có một cơ hội trị con Ông Kẹ...\"\n"
              "Ron cười khẩy:\n"
              "\"Bồ thì sợ cái gì nhứt chứ? Chắc là một bài tập chỉ được chín trên mười điểm chứ gì!\"",
              style: DSTextStyle.ws16w400,
            ),
          ],
        ),
      ),
    );
  }
}
